1.3.4dev: empty action in forms is no longer OK in HTML5
This is done to avoid the following error reported by the nu validator:
{{{
Error: Bad value  for attribute action on element form: Must be non-empty.
}}}

However, we can't remove the action attribute altogether, as this seems
to badly interfer with twill and the functional tests.

Refs #12677.


git-svn-id: https://svn.edgewall.org/repos/trac/trunk@16862 af82e41b-90c4-0310-8c96-b1721e28e2e2